### ISSUE TITLE
PlayfieldComponent' does not contain a definition for 'GlobalScale'

### ISSUE THREAD

**Issue by shntat** [VisualPinball/VisualPinball.Engine.PinMAME#30]
Library\PackageCache\org.visualpinball.engine.pinmame@0.0.1-preview.36\Editor\PinMameGamelogicEngineInspector.cs(249,55): error CS0117: 'PlayfieldComponent' does not contain a definition for 'GlobalScale'

Library\PackageCache\org.visualpinball.engine.pinmame@0.0.1-preview.36\Editor\PinMameGamelogicEngineInspector.cs(250,48): error CS0117: 'PlayfieldComponent' does not contain a definition for 'GlobalScale'

Cannot upgrade the Visual Pinball Engine (HDRP) past 166

Does this require an upgrade of unity from  2021.3.0f1 to a newer version?

![166](https://user-images.githubusercontent.com/12681995/210850333-906bc136-b317-4308-8cb2-64eb7376efd0.png)

![167](https://user-images.githubusercontent.com/12681995/210850357-99cafe59-adcc-4fae-b347-7e001a2383f9.png)

**Comment by shntat** [comment]
Visual Pinball Engine
Version 0.0.1-preview.122 - December 23, 2022 and above Is causing the issue with pinmame

**Comment by freezy** [comment]
Oops, yeah, probably because I forgot to merge the PinMAME branch. Can you update and try again?

**Comment by shntat** [comment]
same error after update.

 Library\PackageCache\org.visualpinball.engine.pinmame@0.0.1-preview.37\Editor\PinMameGamelogicEngineInspector.cs(249,55): error CS0117: 'PlayfieldComponent' does not contain a definition for 'GlobalScale' 

same error after update.

**Comment by shntat** [comment]
I think in might be in the playfieldcomponent.cs  after line 36 GlobalScale seems to be commented out.

![166playfield component](https://user-images.githubusercontent.com/12681995/210864295-5000d722-b3b2-46fa-a3a4-94343c8ebed6.png)

**Comment by shntat** [comment]
that made the error go away but breaks how the flippers rotate.

**Comment by shntat** [comment]
Any other ideas?

**Comment by freezy** [comment]
Update to the latest PinMAME package (v0.0.1-preview.38), it should be fine now. Sorry for the hiccup.

**Comment by shntat** [comment]
Every Thing works now. I had to start a new project some how something changed that broke the physics.
